CREATE DATABASE Bank;
USE Bank;

CREATE TABLE Client (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    Name VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Birth DATE NOT NULL,
    RegisterDate DATETIME NOT NULL DEFAULT GETDATE(),
);

CREATE TABLE AccountType (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    Name VARCHAR (150) NOT NULL,
    RegisterDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE TransactionType (
    ID INT NOT NULL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    RegisterDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Account (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    AccountType INT FOREIGN KEY REFERENCES AccountType(ID),
    ClientID INT FOREIGN KEY REFERENCES Client(ID),
    Balance DECIMAL(10, 2) NOT NULL,
    RegisterDate DATETIME NOT NULL DEFAULT GETDATE()
);


CREATE TABLE BankTransaction (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    AccountID INT NOT NULL FOREIGN KEY REFERENCES Account(ID),
    TransactionType INT NOT NULL FOREIGN KEY REFERENCES TransactionType(ID),
    Amount DECIMAL(10, 2) NOT NULL,
    ExternalAccount INT NULL,
    RegisterDate DATETIME NOT NULL DEFAULT GETDATE()
);